services:
  dexapp:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/jobsportal
      - dev-static-data:/vol/web
    command: >
      sh -c "python jobsportal/manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db-jobsportal
      - DB_NAME=jobsportal
      - DB_USER=jpadmin
      - DB_PASS=123JobsPortal321!
      - HERE_APP_ID=2MQBDIGj8mIhuGqUxEcK
      - HERE_API_KEY=D-Uisa2XQ7s-tv1GrgqVBhq6NAygZBl4zLzj30CoIlc
      - SECRET_KEY=django-insecure-4@yrp!w$7+6lnueg_v_vh+k)p9h@4g**x94+^t6t4nnd%kv89^
      - DEBUG=True
    depends_on:
      - db-jobsportal

  db-jobsportal:
    image: postgres:alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jobsportal
      - POSTGRES_USER=jpadmin
      - POSTGRES_PASSWORD=123JobsPortal321!

volumes:
  dev-db-data:
  dev-static-data:
