# Generated by Django 5.0.1 on 2024-01-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobcandidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='lastDate',
            new_name='last_date',
        ),
    ]
