# Generated by Django 5.0.1 on 2024-01-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userresume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='resume',
            field=models.CharField(null=True),
        ),
    ]
