# Generated by Django 5.0.1 on 2024-01-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userresume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
